name: CI Pipeline Alimentos

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_alimentos
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Esperar MySQL iniciar
      run: sleep 20

    - name: Criar tabela
      run: |
        mysql -h 127.0.0.1 -u root -proot db_alimentos < script.sql

    - name: Rodar testes
      run: |
        pytest

